name: 'Sync Action Status'
description: 'Sync a GitHub Action status from a repository_dispatch event'
author: "Philip De Lorenzo"
inputs:
  gh_token:  # The GitHub token to use for access to the API
    description: 'Your GitHub token'
    required: true
    default: None
  repo:  # The repository to sync the status to
    description: 'The repository to sync the status to'
    required: true
    default: None

#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Action Prerequisites
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Sync Action Status
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        REPO: ${{ inputs.repo }}
      run: |
        python ${{ github.action_path }}/main.py --token $GH_TOKEN --repo $REPO
      shell: bash
