name: 'Sync Action Status'
description: 'Sync a GitHub Action status from a repository_dispatch event'
inputs:
  gh_token:  # The GitHub token to use for access to the API
    description: 'Your GitHub token'
    required: true
    default: None
  repo:  # The repository to sync the status to
    description: 'The repository to sync the status to'
    required: true
    default: None

#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - uses: actions/checkout@v4
      with:
        path: sync-action-status

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: List Files
      run: |
        ls -als .
        ls -als ${{ github.workspace }}
        ls -als .github
        ls -als .github/workflows

      shell: bash

    #- name: Install Action Prerequisites
    #  run: pip install -r ${{ github.workspace }}/requirements.txt
    #  shell: bash
