name: Python Black Fomatting
run-name: Black Formatting

on: 
  push:
    branches:
      - "*"
      - "!master"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Python Black
        run: |
          echo "Running Black..."
          python -m pip install black==23.9.1
          python -m black -t py312 --check --diff .

      - name: Sync Action Status (Ref)
        run: |
           echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label
        if: ${{ github.event.pull_request.merged == true }}

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      - uses: actions-ecosystem/action-push-tag@v1
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          tag: ${{ steps.bump-semver.outputs.new_version }}
          message: '${{ steps.bump-semver.outputs.new_version }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'

