name: Python Black Fomatting
run-name: Black Formatting

on: 
  push:
    branches:
      - "*"
      - "!master"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Python Black
        run: |
          echo "Running Black..."
          python -m pip install black
          python -m black -t py312 --check --diff .
