name: Python Black Fomatting
run-name: Black Formatting

on: 
  push:
    branches:
      - "*"
      - "!master"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Python Black
        run: |
          echo "Running Black..."
          pip install black
          black . --check
