name: Python Black Fomatting\Isort
run-name: Black Formatting\Isort

on: 
  push:
    branches:
      - "*"
      - "!master"

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Python Black
        run: |
          echo "Running Black..."
          python -m pip install black==23.9.1
          python -m black -t py312 --check --diff .

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Python Isort
        run: |
          echo "Running Isort..."
          python -m pip install isort==5.12.0
          python -m isort --check --diff .
