name: Unit Tests
run-name: Unit Tests

on: 
  push:
    branches:
      - "*"

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
    
      - name: Run Tests
        run: |
          echo "Running all unit tests..."
          bash test/run_tests.sh -u
