name: Test Dispatch

on: 
  workflow_dispatch:
    inputs:
      debug:
        description: 'Run the workflow in debug mode'
        required: false
        type: boolean
        default: false

env:
  EVENT_TYPE: test_run
  TARGET_REPO_NAME: test-sync-action-status

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - run: |
        echo "${{ github.actor }}"
        echo "${{ github.repository }}"
        echo "${{ github.repository_owner }}"

    - name: Send a Dispatch to the Test Receiver
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        ORG: ${{ github.repository_owner }}
        REPO: ${TARGET_REPO_NAME}
      run: |
        curl -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -d "{\"event_type\": \"${EVENT_TYPE}\"}" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"

    - uses: philipdelorenzo/sync-action-status@init
      with:
        is_org: false
        gh_token: ${{ secrets.GH_TOKEN }}
        event_type: ${EVENT_TYPE}
        # You must use this action ONLY with repositories that you own
        target_repo: ${{ github.repository_owner }}/${TARGET_REPO_NAME}
        debug: ${{ github.event.inputs.debug }}
